import {
  XIcon,
  ReactIcon,
  NextjsIcon,
  TailwindIcon,
  MongoDbIcon,
  PostgresIcon,
  SqlIcon,
  HtmlIcon,
  CssIcon,
  JsIcon,
  TsIcon,
  NpmIcon,
  ReduxIcon,
  GraphQlIcon,
  ExpressIcon,
  DevIcon,
  SassIcon,
  WebPackIcon,
  DockerIcon,
  GitIcon,
  GoogleIcon,
  GitHubIcon,
  PythonIcon,
  AppleIcon,
  NetflixIcon,
  SpotifyIcon,
  GoogleColoredIcon,
  GitHubColorIcon,
  YouTubeIcon,
  ChatGPTIcon,
  ClerkIcon,
  KubernetesIcon,
  LinuxIcon,
  UbuntuIcon,
  ArchLinuxIcon,
  MintLinuxIcon,
  FaceBookIcon,
  InstagramIcon,
  LinkedinIcon,
  SnapChatIcon,
  TwitterBirdIcon,
  NodejsIcon,
  AngularIcon,
  VuejsIcon,
  NuxtjsIcon,
  BootStrapIcon,
  DjangoIcon,
  SpringIcon,
  SpringBootIcon,
  PHPIcon,
  LangChainIcon,
  FireBaseIcon,
  MicrosoftIcon,
  NvidiaIcon,
  MetaIcon,
  NotionIcon,
  RollupIcon,
  ViteIcon,
  SnowpackIcon,
  ESbuildIcon,
  AndroidIcon,
  SwiftIcon,
  IOSIcon,
  AppStoreIcon,
  AppleMusicIcon,
  CplusplusIcon,
  MotionIcon,
  DiscordIcon,
  GoogleMapsIcon,
  FlutterIcon,
  RustIcon,
  FlaskIcon,
  NvimIcon,
  VimIcon,
} from "./icons";

export const normalIcons = [
  { name: "reacticon", icon: <ReactIcon />, iconName: "ReactIcon" },
  { name: "nextjsicon", icon: <NextjsIcon />, iconName: "NextjsIcon" },
  { name: "tailwindicon", icon: <TailwindIcon />, iconName: "TailwindIcon" },
  { name: "mongodbicon", icon: <MongoDbIcon />, iconName: "MongoDbIcon" },
  { name: "postgresicon", icon: <PostgresIcon />, iconName: "PostgresIcon" },
  { name: "sqlicon", icon: <SqlIcon />, iconName: "SqlIcon" },
  { name: "htmlicon", icon: <HtmlIcon />, iconName: "HtmlIcon" },
  { name: "cssicon", icon: <CssIcon />, iconName: "CssIcon" },
  { name: "jsicon", icon: <JsIcon />, iconName: "JsIcon" },
  { name: "tsicon", icon: <TsIcon />, iconName: "TsIcon" },
  { name: "npmicon", icon: <NpmIcon />, iconName: "NpmIcon" },
  { name: "reduxicon", icon: <ReduxIcon />, iconName: "ReduxIcon" },
  { name: "graphqlicon", icon: <GraphQlIcon />, iconName: "GraphQlIcon" },
  { name: "expressicon", icon: <ExpressIcon />, iconName: "ExpressIcon" },
  { name: "devicon", icon: <DevIcon />, iconName: "DevIcon" },
  { name: "webpackicon", icon: <WebPackIcon />, iconName: "WebPackIcon" },
  { name: "sassicon", icon: <SassIcon />, iconName: "SassIcon" },
  { name: "dockericon", icon: <DockerIcon />, iconName: "DockerIcon" },
  { name: "xicon", icon: <XIcon />, iconName: "XIcon" },
  { name: "giticon", icon: <GitIcon />, iconName: "GitIcon" },
  { name: "googleicon", icon: <GoogleIcon />, iconName: "GoogleIcon" },
  { name: "githubicon", icon: <GitHubIcon />, iconName: "GitHubIcon" },
  { name: "pythonicon", icon: <PythonIcon />, iconName: "PythonIcon" },
  { name: "appleicon", icon: <AppleIcon />, iconName: "AppleIcon" },
  { name: "netflixicon", icon: <NetflixIcon />, iconName: "NetflixIcon" },
  { name: "spotifyicon", icon: <SpotifyIcon />, iconName: "SpotifyIcon" },
  { name: "githubcoloricon", icon: <GitHubColorIcon />, iconName: "GitHubColorIcon" },
  { name: "youtubeicon", icon: <YouTubeIcon />, iconName: "YouTubeIcon" },
  { name: "chatgpticon", icon: <ChatGPTIcon />, iconName: "ChatGPTIcon" },
  { name: "clerkicon", icon: <ClerkIcon />, iconName: "ClerkIcon" },
  { name: "kubernetesicon", icon: <KubernetesIcon />, iconName: "KubernetesIcon" },
  { name: "linuxicon", icon: <LinuxIcon />, iconName: "LinuxIcon" },
  { name: "ubuntuicon", icon: <UbuntuIcon />, iconName: "UbuntuIcon" },
  { name: "archlinuxicon", icon: <ArchLinuxIcon />, iconName: "ArchLinuxIcon" },
  { name: "mintlinuxicon", icon: <MintLinuxIcon />, iconName: "MintLinuxIcon" },
  { name: "facebookicon", icon: <FaceBookIcon />, iconName: "FaceBookIcon" },
  { name: "instagramicon", icon: <InstagramIcon />, iconName: "InstagramIcon" },
  { name: "iinkedinicon", icon: <LinkedinIcon />, iconName: "LinkedinIcon" },
  { name: "snapchaticon", icon: <SnapChatIcon />, iconName: "SnapChatIcon" },
  { name: "twitterbirdicon", icon: <TwitterBirdIcon />, iconName: "TwitterBirdIcon" },
  { name: "nodejsicon", icon: <NodejsIcon />, iconName: "NodejsIcon" },
  { name: "angularicon", icon: <AngularIcon />, iconName: "AngularIcon" },
  { name: "vuejsicon", icon: <VuejsIcon />, iconName: "VuejsIcon" },
  { name: "nuxtjsicon", icon: <NuxtjsIcon />, iconName: "NuxtjsIcon" },
  { name: "djangoicon", icon: <DjangoIcon />, iconName: "DjangoIcon" },
  { name: "bootstrapicon", icon: <BootStrapIcon />, iconName: "BootStrapIcon" },
  { name: "springicon", icon: <SpringIcon />, iconName: "SpringIcon" },
  { name: "springbooticon", icon: <SpringBootIcon />, iconName: "SpringBootIcon" },
  { name: "phpicon", icon: <PHPIcon />, iconName: "PHPIcon" },
  { name: "langchainicon", icon: <LangChainIcon />, iconName: "LangChainIcon" },
  { name: "firebaseicon", icon: <FireBaseIcon />, iconName: "FireBaseIcon" },
  { name: "microsofticon", icon: <MicrosoftIcon />, iconName: "MicrosoftIcon" },
  { name: "nvidiaicon", icon: <NvidiaIcon />, iconName: "NvidiaIcon" },
  { name: "metaicon", icon: <MetaIcon />, iconName: "MetaIcon" },
  { name: "notioicon", icon: <NotionIcon />, iconName: "NotionIcon" },
  { name: "rollupicon", icon: <RollupIcon />, iconName: "RollupIcon" },
  { name: "viteicon", icon: <ViteIcon />, iconName: "ViteIcon" },
  { name: "snowpackicon", icon: <SnowpackIcon />, iconName: "SnowpackIcon" },
  { name: "ESbuildIcon", icon: <ESbuildIcon />, iconName: "ESbuildIcon" },
  { name: "androidicon", icon: <AndroidIcon />, iconName: "AndroidIcon" },
  { name: "swifticon", icon: <SwiftIcon />, iconName: "SwiftIcon" },
  { name: "iosicon", icon: <IOSIcon />, iconName: "IOSIcon" },
  { name: "appstoreicon", icon: <AppStoreIcon />, iconName: "AppStoreIcon" },
  { name: "applemusicicon", icon: <AppleMusicIcon />, iconName: "AppleMusicIcon" },
  { name: "cplusplusicon", icon: <CplusplusIcon />, iconName: "CplusplusIcon" },
  { name: "motionicon", icon: <MotionIcon />, iconName: "MotionIcon" },
  { name: "discordicon", icon: <DiscordIcon />, iconName: "DiscordIcon" },
  { name: "googlemapsicon", icon: <GoogleMapsIcon />, iconName: "GoogleMapsIcon" },
  { name: "flutteicon", icon: <FlutterIcon />, iconName: "FlutterIcon" },
  { name: "rusticon", icon: <RustIcon />, iconName: "RustIcon" },
  { name: "flaskicon", icon: <FlaskIcon />, iconName: "FlaskIcon" },
  { name: "nvimicon", icon: <NvimIcon />, iconName: "NvimIcon" },
  { name: "vimicon", icon: <VimIcon />, iconName: "VimIcon" },

];
